from langchain.agents import create_agent
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from src.genai.multi_agent.tools.tools import web_search, scrape_url
from dotenv import load_dotenv

load_dotenv()


# model initialization
chat_groq = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0,
)

# the first agent: search agent
def build_search_agent():
    return create_agent(
        model=chat_groq,
        tools=[web_search],
    )

# second agent: reader agent
def build_reader_agent():
    return create_agent(
        model=chat_groq,
        tools=[scrape_url],
    )


# writer chain

writer_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        "You are an expert research writer. write clean and concise research report based on the information provided by the search and reader agents. Ensure that the report is well-structured, with clear headings and subheadings, and that it accurately reflects the information gathered from the sources.",
    ),
    (
        "human",
        """
        Write a detailed research report based on the information provided by the search and reader agents. 
        Ensure that the report is well-structured, with clear headings and subheadings, 
        and that it accurately reflects the information gathered from the sources.
        Topic: {topic}
        Research Gathered: {research}
        Structure the report as:
        - Introduction 
        - Key Findings (minimum  3 well-explained points)
        - Conclusion
        - Sources (list all sources used in the research)

        Be detailed, factual and professional.
        """,
    ),
])

writer_chain = writer_prompt | chat_groq | StrOutputParser()

# critic_chain
critic_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        "You are a critical reviewer. Your task is to evaluate the research report generated by the writer agent. Provide constructive feedback on the clarity, accuracy, and depth of the report. Suggest improvements where necessary.",
    ),
    (
        "human",
        """
        Review the research report below and evaluate it strictily.
        Report:
        {report}

        Respond in this exact format:
        Score: X/10

        Strengths:
        - ...
        - ...

        Areas to Improve:
        - ...
        - ...
        Suggestions:
        - ...

        One line verdict: ...
        """,
    ),
])


critic_chain = critic_prompt | chat_groq | StrOutputParser()




